server:
  port: 9000 #服务注册中心端口号
spring:
  application:
    name: zuul-service


eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka  #注册 中心已经开启认证

  instance:
    instance-id: ${spring.cloud.client.ip-address}:${server.port}:${spring.application.name}
    prefer-ip-address: true
logging:
  level:
    com:
      netflix:
        eureka: OFF
        discovery: OFF
zuul:
  ignored-services: "*"
  routes:
    product-service:
      path: /product-service/**
      serviceId: product-service
      stripPrefix: true
      ignored-patterns:
        - /test/*
      sensitiveHeaders:  # 置空该属性的值即可
    order-service:
      path: /order-service/**
      serviceId: order-service
      stripPrefix: true
      ignored-patterns:
        - /test/*
      sensitiveHeaders:  # 置空该属性的值即可
    gross-settlement-service:
      path: /gross-settlement-service/**
      serviceId: gross-settlement-service
      stripPrefix: true
      ignored-patterns:
        - /test/*
      sensitiveHeaders:  # 置空该属性的值即可
